name: gemini_api_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_gemini: ^3.0.0
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  equatable: ^2.0.7
  flutter_dotenv: ^6.0.0
  markdown_widget: ^2.3.2+8


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
